### ISSUE TITLE
Remove chatId from the URL parameters

### ISSUE THREAD

**Issue by arcmena** [grandmont/kordy-app#7]
## Description

Remove the chatId from the URL params to prevent the user from connecting into the room.

## Implementation

- Remove the chatId from the URL
- Remove useEffect of the chatId param
- Add the chatId from the _join-waiting-list_ response in the ChatContext
- Retrieve the chatId from the ChatContext

**Comment by gabepereira** [comment]
## What happened so far...

I made a lot of changes in the waiting list, to match the logic in the web application. Like removing the ChatContext component (which was pretty useless) and using the ChatView as the logical component to the entire Chat section.

I'm still testing the changes but it's working well right now.

I'll be waiting for your approve @arcmena.
